package org.example.project.data.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Event(
    val id: String,
    @SerialName("creator_id") val creatorId: String? = null,
    @SerialName("group_id") val groupId: String? = null,
    val title: String,
    val description: String? = null,
    @SerialName("location_name") val locationName: String,
    val lat: Double,
    val lng: Double,
    @SerialName("date_time") val dateTime: String,
    @SerialName("max_participants") val maxParticipants: Int = 10,
    @SerialName("is_public") val isPublic: Boolean = true,
    @SerialName("key_interests") val keyInterests: List<Int>? = null,
    @SerialName("created_at") val createdAt: String? = null
)

// Used for creating a new event — id and created_at are generated by the DB.
@Serializable
data class EventInsert(
    @SerialName("creator_id") val creatorId: String,
    @SerialName("group_id") val groupId: String? = null,
    val title: String,
    val description: String? = null,
    @SerialName("location_name") val locationName: String,
    val lat: Double,
    val lng: Double,
    @SerialName("date_time") val dateTime: String,
    @SerialName("max_participants") val maxParticipants: Int = 10,
    @SerialName("is_public") val isPublic: Boolean = true,
    @SerialName("key_interests") val keyInterests: List<Int>? = null
)

@Serializable
enum class ParticipantStatus {
    @SerialName("joined") joined,
    @SerialName("pending") pending,
    @SerialName("declined") declined
}

@Serializable
data class EventParticipant(
    @SerialName("event_id") val eventId: String,
    @SerialName("profile_id") val profileId: String,
    val status: ParticipantStatus = ParticipantStatus.joined,
    @SerialName("joined_at") val joinedAt: String? = null
)
